SELECT
    p.PRODUCT_NUMBER,
    p.PRODUCT_NAME,
    COUNT(ri.RETURN_CODE) AS NumberOfReturns,
    SUM(ri.RETURN_QUANTITY) AS TotalQuantityReturned
FROM
    dbo.RETURNED_ITEM ri
    LEFT JOIN dbo.ORDER_DETAILS od ON ri.ORDER_DETAIL_CODE = od.ORDER_DETAIL_CODE
    LEFT JOIN dbo.PRODUCT p ON od.PRODUCT_NUMBER = p.PRODUCT_NUMBER
GROUP BY
    p.PRODUCT_NUMBER,
    p.PRODUCT_NAME
ORDER BY
    p.PRODUCT_NUMBER;